import { symbol, type Expression, type Pose } from "../../../brand/mascot.mjs";

type MascotProps = {
  expr?: Expression;
  pose?: Pose;
  prop?: "stamp" | "magnifier";
  dark?: boolean;
};

// Variant file generated by scripts/gen-mascots.mjs (prebuild) into public/m/.
export function mascotSrc({ expr = "skeptic", pose = "down", prop, dark = false }: MascotProps) {
  const p = pose === "point" ? prop : undefined;
  return `/m/${[expr, pose, p, dark ? "dark" : ""].filter(Boolean).join("-")}.svg`;
}

// The mascot as a cached SVG image (eyes blink inside the file). Keeps HTML small.
export function Mascot({
  className,
  label,
  priority = false,
  ...variant
}: MascotProps & { className?: string; label?: string; priority?: boolean }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={mascotSrc(variant)}
      alt={label ?? ""}
      width={400}
      height={600}
      className={className}
      loading={priority ? "eager" : "lazy"}
      decoding="async"
      {...(priority ? { fetchPriority: "high" as const } : {})}
    />
  );
}

export function LogoMark({ className, bg }: { className?: string; bg?: string }) {
  const svg = symbol({ bg }).replace("<svg ", `<svg class="${className ?? ""}" aria-hidden="true" `);
  return <span className="inline-flex shrink-0" dangerouslySetInnerHTML={{ __html: svg }} />;
}
