// Environment access. Secrets live only in Vercel env (set by the owner or generated by setup scripts) —
// never in the repository, never sent to the browser.
export const env = {
  get databaseUrl() {
    // DATABASE_URL: a database dedicated to CHEK (or a role restricted to schema chek). Set by the owner in Vercel.
    return process.env.DATABASE_URL || process.env.POSTGRES_URL || null;
  },
  get appSecret() {
    return process.env.APP_SECRET || null; // HMAC for sessions/state
  },
  get cronSecret() {
    return process.env.CRON_SECRET || null; // pg_cron → /api/cron
  },
  get adminToken() {
    return process.env.ADMIN_TOKEN || null; // local owner dashboard → /api/admin
  },
  get telegramToken() {
    return process.env.TELEGRAM_BOT_TOKEN || null; // owner creates the bot with @BotFather
  },
  get telegramWebhookSecret() {
    return process.env.TELEGRAM_WEBHOOK_SECRET || null; // generated; checked on every webhook call
  },
  get xClientId() {
    return process.env.X_CLIENT_ID || null;
  },
  get xClientSecret() {
    return process.env.X_CLIENT_SECRET || null;
  },
  get anthropicKey() {
    return process.env.ANTHROPIC_API_KEY || null;
  },
  get solanaRpc() {
    return process.env.SOLANA_RPC || "https://api.mainnet-beta.solana.com";
  },
  get siteUrl() {
    return process.env.SITE_URL || "https://chekcoin.vercel.app";
  },
};

// Which integrations are configured (names only — values are never exposed).
export function integrations() {
  return {
    database: Boolean(env.databaseUrl),
    cron: Boolean(env.cronSecret),
    admin: Boolean(env.adminToken),
    telegram: Boolean(env.telegramToken && env.telegramWebhookSecret),
    x: Boolean(env.xClientId && env.xClientSecret),
    ai: Boolean(env.anthropicKey),
  };
}
